from enum import Enum

class SEPARAZIONE_DATI(Enum): 
    ID="by_id"

class ENTITY(Enum):
    ATTACKER="attacker"
    VICTIM="victim"
    PROXY="proxy"

class MSG(Enum):
    CONFIRM_ATTACKER="__CONFIRM_ATTACKER__"
    CONFIRM_VICTIM="__CONFIRM_VICTIM__"
    CONFIRM_PROXY="__CONFIRM_PROXY__"
    CONFIRM_COMMAND="__CONFIRM_COMMAND__"
    ATTACK_FUNCTION="__ATTACK_FUNCTION__"
    LAST_PACKET="__LAST_PACKET__"
    WAIT_DATA="__WAIT_DATA__"
    END_COMMUNICATION="__END_COMMUNICATION__"
    END_DATA="__END_DATA__"
    START_SOURCES="__START_SOURCES__"
    END_SOURCES="__END_SOURCES__" 
    END_SOCKETSEND="__END_SEND__"